// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Comp1: typeof import('./src/components/comp1.vue')['default']
    Comp2: typeof import('./src/components/comp2.vue')['default']
    Comp3: typeof import('./src/components/comp3.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    INPute: typeof import('./src/components/INPute.vue')['default']
  }
}

export { }
